--===Analysis status.
--Total exceptions count
SELECT count(1) as TotalCount  FROM  EXCEPTIONFRAGMENT;
--Analysis completed count
SELECT count(1) as CompletedCount  FROM  EXCEPTIONFRAGMENT F where F.ANALYSISCOMPLETED = TRUE;
--To be analysized
SELECT count(1) ToBeAnalysized  FROM  EXCEPTIONFRAGMENT F where F.ISMATCHED = FALSE AND F.ANALYSISCOMPLETED = FALSE;
--No rules for exceptions
SELECT count(1) NoRulesCount  FROM  EXCEPTIONFRAGMENT F where F.ISMATCHED = TRUE AND F.ANALYSISCOMPLETED = FALSE;

--===Exceptions frequency of occurrence report.
SELECT T.TITLE, T.RCA, COUNT(*) AS TIMES from EXCEPTIONFRAGMENT AS F 
LEFT JOIN TEMPLATEEXCEPTIONFRAGMENT AS R 
ON F.ID = R.FRAGMENTID 
LEFT JOIN TEMPLETE AS T
ON R.TEMPID = T.ID
--WHERE F.DATE BETWEEN  '2013-04-01' AND '2013-04-30'
GROUP BY T.ID, T.TITLE, T.RCA
ORDER BY TIMES DESC;

--===Exceptions' RCA details.
SELECT T.TITLE, T.RCA, F.DATE FROM EXCEPTIONFRAGMENT AS F 
LEFT JOIN TEMPLATEEXCEPTIONFRAGMENT AS R 
ON F.ID = R.FRAGMENTID 
LEFT JOIN TEMPLETE AS T
ON R.TEMPID = T.ID
WHERE F.DATE BETWEEN  '2013-04-01' AND '2013-04-30';
ORDER BY F.DATE DESC;

--===Exceptions analysis completed.
SELECT T.TITLE, T.RCA, F.DATE FROM EXCEPTIONFRAGMENT AS F 
LEFT JOIN TEMPLATEEXCEPTIONFRAGMENT AS R 
ON F.ID = R.FRAGMENTID 
LEFT JOIN TEMPLETE AS T
ON R.TEMPID = T.ID
WHERE F.ANALYSISCOMPLETED = TRUE;

--===These exceptions should define rules to analysize them.
SELECT T.TITLE, T.RCA, F.DATE FROM EXCEPTIONFRAGMENT AS F 
LEFT JOIN TEMPLATEEXCEPTIONFRAGMENT AS R 
ON F.ID = R.FRAGMENTID 
LEFT JOIN TEMPLETE AS T
ON R.TEMPID = T.ID
WHERE F.ISMATCHED = TRUE AND F.ANALYSISCOMPLETED = FALSE;

--===Logger file exceptions details.
SELECT L.fiLENAME, L.WHICHDAY, T.NAME, T.TITLE, T.RCA FROM LOGGERFILE L
JOIN EXCEPTIONFRAGMENT E
ON L.ID = E.LOGFILEID
JOIN TEMPLATEEXCEPTIONFRAGMENT TE
ON E.ID = TE.FRAGMENTID 
JOIN TEMPLETE T
ON TE.TEMPID = T.ID

--===Report the amount of exceptions for a logger file.
SELECT L.fiLENAME, COUNT(E.ID) AS EXCEPTIONCOUNT FROM LOGGERFILE L
JOIN EXCEPTIONFRAGMENT E
ON L.ID = E.LOGFILEID
JOIN TEMPLATEEXCEPTIONFRAGMENT TE
ON E.ID = TE.FRAGMENTID 
JOIN TEMPLETE T
ON TE.TEMPID = T.ID
--WHERE L.WHICHDAY  BETWEEN  '2012-12-01' AND   '2012-12-31' 
GROUP BY L.fiLENAME
--ORDER BY EXCEPTIONCOUNT DESC

--===Get exceptions report in some day or month.
SELECT L.fiLENAME, T.TITLE, T.RCA AS EXCEPTIONS FROM LOGGERFILE L
JOIN EXCEPTIONFRAGMENT E
ON L.ID = E.LOGFILEID
JOIN TEMPLATEEXCEPTIONFRAGMENT TE
ON E.ID = TE.FRAGMENTID 
JOIN TEMPLETE T
ON TE.TEMPID = T.ID
--WHERE L.WHICHDAY  BETWEEN  '2012-12-01' AND   '2012-12-31' 




